### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by peterpt** [shenril/Sitadel#10]
Congratulations , this is one of the best cli security scanners i have seen on the web .
Very nice work .
Thank you for the contribution

**Comment by shenril** [comment]
@peterpt Thanks for the love! 
It's still a work in progress and I hope to make it much better in the near future! 
I do recommend you take a look at nikto , skipfish and WAScan if you like CLI security scanner :) 
Have a great day

**Comment by peterpt** [comment]
Thanks for the tips
