### ISSUE TITLE
error on Sitadel installation

### ISSUE THREAD

**Issue by NRGLine4Sec** [shenril/Sitadel#22]
add "pip3 install scrapy" to install Sitadel without errors

**Comment by shenril** [comment]
I believe scrapy is already listed in the dependencies 
https://github.com/shenril/Sitadel/blob/master/setup.py#L39
@NRGLine4Sec how did you install Sitadel?

**Comment by shenril** [comment]
I enforced pip3 in case you used pip2 by default
This should solve the misunderstanding in the future
