### ISSUE TITLE
When running Sitadel a warning message is thrown about deprecating default Loader

### ISSUE THREAD

**Issue by q2dg** [shenril/Sitadel#23]
Specifically, the message is:

_"Sitadel/lib/config/settings.py:48: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(yamlfile)_

Thanks

**Comment by shenril** [comment]
Thank you for reporting this ! 
I'm working on the fix

**Comment by shenril** [comment]
@q2dg 
The PR was merged so it should be fine now

**Comment by q2dg** [comment]
Yes, it's true!!!
Thanks a lot!!!
