### ISSUE TITLE
Sitadel hangs at "checking common backdoors" step

### ISSUE THREAD

**Issue by q2dg** [shenril/Sitadel#25]
I run _python3 sitadel.py http://www.mijacllefia.org_ and, after launching attack modules and checking admin interfaces, it hangs at checking common backdoors: I've waited more than twenty minutes and it stills is there without showing anything more on screen.
Thanks.

**Comment by shenril** [comment]
I'll see to improve verbosity level to get more feedback on the screen 

About the time it could be a lot of reasons: Web Application Firewall/timeout/blacklisting

**Comment by shenril** [comment]
Could you re-run the scan with the verbosity on ?
`python3 sitadel.py http://www.mijacllefia.org -v `
And tell me if it blocks somewhere

**Comment by q2dg** [comment]
Sure!
The output is exactly the same with -v argument or without it :-(
Thanks anyway!

**Comment by q2dg** [comment]
Thanks!
It hangs at "Testing: http://www.mijacllefia.org/c99shell.php" and it doesn't show nothing more.

**Comment by shenril** [comment]
I believe this is related to the request timeout. 
By default sitadel is going to wait for the server answer forever. 
In your case you should specify a timeout like 10 seconds
`python3 sitadel.py http://www.mijacllefia.org -v -t 10`

I could enable a default timeout for these cases
Anyway it means that something might be wrong on your website though.
I m only doing a HEAD request on c99.php and the server never answers.... So there might be a problem on server side.

**Comment by q2dg** [comment]
You were right, thanks! 
Maybe eanbling a default timeout it's a good idea, yes.
Anyway I ended having two kinds of errors, which are shown in attached screenshots and no results. :-(
But since this is not related to initial issue, I'll close it. Feel free to open again if you consider it.
Thanks a lot!

![Screenshot1](https://user-images.githubusercontent.com/7274874/56437898-6ac57580-62e1-11e9-880b-bd0f928983e0.png)
![Screenshot2](https://user-images.githubusercontent.com/7274874/56437899-6b5e0c00-62e1-11e9-9bee-6bb6dd7d91f9.png)
