### ISSUE TITLE
what is true payload ?

### ISSUE THREAD

**Issue by Phoenix1112** [shenril/Sitadel#28]
hello. thank your for this project. I did a scan with sitadel for the target site. i did change xss.list.. The sitadel program tells me there is an xss vulnerability..sitadel does not show which xss payload it finds. There are 1500 xss loads in my payload list..How do we know which payload is correct? 

it just shows an address like this. 

That site is may be vulnerable to Cross Site Scripting (XSS) at https://example.com/category=5

how do we know which payload it uses?

**Comment by shenril** [comment]
Thank you for the feedback
Working on it on #29 
I'll try to merge it this week

**Comment by Phoenix1112** [comment]
Ok

**Comment by shenril** [comment]
I merged it but I couldn't reproduce your message on example.com 
Do you mind sharing how you scanned it ?

**Comment by Phoenix1112** [comment]
sudo python3 sitadel.py https://example.com/category=5 --no-redirect

**Comment by shenril** [comment]
I ran sitadel with the same options but it does not trigger anything to me 
Do you have a proxy or something in the middle that would interfere with the results?

Regarding the feature request it has been implemented so you can validate it for your use-case

**Comment by Phoenix1112** [comment]
i am not use proxy.. have you updated the program? If you updated it, I haven't used the new version yet.
if this program claims that it has found an xss vulnerability, it must show which payload has found the xss vulnerability.

this is my channel... I shared a video about sitadel.. video does not show the payload of the vulnerability.

https://www.youtube.com/watch?v=r03NRoBAn3M

**Comment by shenril** [comment]
Oh thank you so much for presenting this tool in your video. 
Yes I pushed the changes and created version 0.1.1 
Can you update the code and give it a try?

**Comment by shenril** [comment]
Since the work was done, I 'll close this for now
Let me know if something didn't t work for you
