### ISSUE TITLE
no-redirect: confusing message

### ISSUE THREAD

**Issue by blshkv** [shenril/Sitadel#38]
Hi, I'm running the tool with ```--no-redirect``` parameter, however there is an info message:
```[i] For better waf detection we recommend you to run with --no-redirect```
in the output.

This is confusing. Was my parameter skipped for some reason?

**Comment by shenril** [comment]
The parameter is taken into account but the waf modules loaded just can t see this parameter and displays this message by default all the time

I can work on fix if it bothers :)

**Comment by shenril** [comment]
Working on it in #39
