### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Niccolum** [shenril/Sitadel#40]
Hello
I see you haven't docs for your project
I write study project with sphinx, which generate docs as you wish

Here is it: https://github.com/Niccolum/intrst_algrms
https://intrst-algrms.readthedocs.io/en/latest/index.html

For my docs helps two projects:
https://github.com/inveniosoftware/flask-sso/tree/master/docs
And
https://github.com/aio-libs/aiohttp/tree/master/docs

Maybe all of it helps you too.
Thanks

**Comment by shenril** [comment]
Not looking for that kind of docs for the moment
Thank you for your issue
