### ISSUE TITLE
How to calculate Low , medium , high of risk level ?

### ISSUE THREAD

**Issue by nicejava** [shenril/Sitadel#44]
How to calculate Low , medium , high of risk level ? i don't know sitadel where function return output .. thank you

**Comment by shenril** [comment]
Hello ! 

Actually low , medium and high is how much impact the plugin has on the target. 
- Low is only reading information with no impact on target
- Medium is doing requests on the target and possibly interacting with the logic but without harmful requests
- High is requests potentially harmful that could destroy or change the data on the target system (drop database in sql injection for instance)

I recommend medium for production system and high in test environment for better testing. 

Let me know if you have other questions.

**Comment by nicejava** [comment]
How to run sitadel get output of result after attack  ? Where function or
line in your code

เมื่อ พ. 7 เม.ย. 2564 เวลา 15:18 Shenril ***@***.***>
เขียนว่า:

**Comment by shenril** [comment]
The result should be actually inside the console or you can also check the log file that is created : sitadel.log

**Comment by nicejava** [comment]
Thank you

เมื่อ จ. 12 เม.ย. 2564 เวลา 12:42 Shenril ***@***.***>
เขียนว่า:

**Comment by shenril** [comment]
No problem

**Comment by nicejava** [comment]
How to scan with CVE vulscan ?
What use command please example for run CVE

เมื่อ จ. 12 เม.ย. 2564 เวลา 17:02 Shenril ***@***.***>
เขียนว่า:

**Comment by shenril** [comment]
sitadel is dedicated to web scanning, so we can't have all CVE. 

I included some CVE tests in https://github.com/shenril/Sitadel/tree/master/lib/modules/attacks/vulns

But that is not exhaustive
