### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MoBasheer** [shenril/Sitadel#6]
Hi all, 

I try to use Sitadel, I have installed it successfully, but when I run it, I get the following error message:
 
Traceback (most recent call last):
  File "sitadel.py", line 14, in <module>
    from lib.config import settings
  File "/mnt/c/Users/M.Basheer/Desktop/Sitadel/lib/config/__init__.py", line 1, in <module>
    from .settings import Settings
  File "/mnt/c/Users/M.Basheer/Desktop/Sitadel/lib/config/settings.py", line 50
    cls.cfg = {**cls.cfg, **config}
                ^
SyntaxError: invalid syntax

Can someone please help me to explain how I can solve that?

Thanks in advance.

**Comment by PierrePaul** [comment]
Can you give us the output of ```python --version```?
From the path of your files, I'm guessing your running the project through bash for windows?

**Comment by MoBasheer** [comment]
Thank you very much for your response!
Yes correct, I'm using bash for windows, the output of "python --version" is Python 2.7.15rc1. 
Do I have any opportunity to solve this issue?
Thanks again!

**Comment by PierrePaul** [comment]
Python3.x seems to be a requirement. Maybe try ```python3 sitadel.py <url>``` ?

**Comment by shenril** [comment]
Hello , 
Indeed Sitadel is intended to work on Python3 
At this moment I have no plan to backport it to Python2
