### ISSUE TITLE
ImportError: No module named 'incremental'

### ISSUE THREAD

**Issue by richdev135** [shenril/Sitadel#7]
Trying to run Sitadel. It's never run successfully for me.  I get a stack trace (see below).  I'm running python3 or 3.5. Same results with either version.  
OS: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="LXLE Eclectica 16.04.4 64-bit"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"

Here's the stack trace:
python3 sitadel.py --help
Traceback (most recent call last):
  File "sitadel.py", line 17, in <module>
    from lib.utils import banner, manager, output, validator
  File "/media/qwerty/OS/Linux/Dev/python-code/Sitadel/lib/utils/manager.py", line 3, in <module>
    from lib.modules.crawler.crawler import crawl
  File "/media/qwerty/OS/Linux/Dev/python-code/Sitadel/lib/modules/crawler/crawler.py", line 3, in <module>
    import scrapy
  File "/usr/local/lib/python3.5/dist-packages/Scrapy-1.5.1-py3.5.egg/scrapy/__init__.py", line 27, in <module>
    from . import _monkeypatches
  File "/usr/local/lib/python3.5/dist-packages/Scrapy-1.5.1-py3.5.egg/scrapy/_monkeypatches.py", line 20, in <module>
    import twisted.persisted.styles  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/Twisted-18.9.0-py3.5-linux-x86_64.egg/twisted/__init__.py", line 11, in <module>
    from twisted._version import __version__ as version
  File "/usr/local/lib/python3.5/dist-packages/Twisted-18.9.0-py3.5-linux-x86_64.egg/twisted/_version.py", line 8, in <module>
    from incremental import Version
ImportError: No module named 'incremental'

Thanks in Advance!

**Comment by shenril** [comment]
Currently having a problem with scrapy, the library used for crawling the URLs 
It appears their python3 support has dropped due to twisted ... 
I ll open a ticket on their end about that and meanwhile I may have to code a crawler to replace this library

**Comment by shenril** [comment]
The current library i m using for crawling the URLs seems to have broken their compatbility with python3 ... i ll have to find a replacement 
Looking at my travis build however python3.5 seems to work ...

**Comment by shenril** [comment]
Memo
```
lib/modules/crawler/crawler.py:3: in <module>
    import scrapy
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/scrapy/__init__.py:34: in <module>
    from scrapy.spiders import Spider
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/scrapy/spiders/__init__.py:10: in <module>
    from scrapy.http import Request
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/scrapy/http/__init__.py:11: in <module>
    from scrapy.http.request.form import FormRequest
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/scrapy/http/request/form.py:17: in <module>
    from scrapy.utils.response import get_base_url
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/scrapy/utils/response.py:10: in <module>
    from twisted.web import http
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/web/http.py:100: in <module>
    from twisted.internet import interfaces, protocol, address
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/address.py:103: in <module>
    class UNIXAddress(object):
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/address.py:111: in UNIXAddress
    name = attr.ib(converter=attr.converters.optional(_asFilesystemBytes))
E   TypeError: attrib() got an unexpected keyword argument 'converter'
```

**Comment by shenril** [comment]
problems occurs in 3.6.3 which is stable for Python3 at the moment , but seems to go fine with 3.6.6

**Comment by shenril** [comment]
Tests have been passing for python 3.5, 3.6 and 3.7
I m closing this ticket for now
