### ISSUE TITLE
few errors

### ISSUE THREAD

**Issue by sk3lk0** [shenril/Sitadel#8]
test on python3.6
[+] Found "/" directory at http://example.com/
cannot use a string pattern on a bytes-like object
[i] Checking common files...
Cannot mix str and non-str arguments
[i] Checking common log files..
Cannot mix str and non-str arguments
[i] Checking html injection...
[i] Checking ldap injection...
[i] Checking php code injection...
[i] Checking remote file inclusion...
[i] Checking sql injection...
[i] Checking xpath injection...
[i] Checking cross site scripting...
[i] Scanning anonymous cipher vuln...
a bytes-like object is required, not 'str'
[i] Scanning crime (SPDY) vuln...
a bytes-like object is required, not 'str'
[i] Scanning shellshock vuln..
nothing to repeat at position 0
[i] Scanning struts-shock vuln..
nothing to repeat at position 0
[i] Checking http allow methods..
'list' object has no attribute 'upper'
[i] Checking webdav..
cannot use a string pattern on a bytes-like object
[i] Checking html object..
cannot use a string pattern on a bytes-like object
[i] Checking listing..
[i] Checking multiple index..
Cannot mix str and non-str arguments
Traceback (most recent call last):
  File "sitadel.py", line 93, in <module>
    Sitadel().main()
  File "sitadel.py", line 88, in main
    self.ma.attacks(args.attack, self.url, discovered_urls)
  File "/wd/lib/utils/manager.py", line 29, in attacks
    Attacks(url, crawled_urls).run(plugins)
  File "/wd/lib/modules/attacks/__init__.py", line 45, in run
    raise (e)
  File "/wd/lib/modules/attacks/__init__.py", line 39, in run
    attacks = ([(p(), p().process(self.start_url, self.crawled_urls)) for p in AttackPlugin.plugins])
  File "/wd/lib/modules/attacks/__init__.py", line 39, in <listcomp>
    attacks = ([(p(), p().process(self.start_url, self.crawled_urls)) for p in AttackPlugin.plugins])
  File "/wd/lib/modules/attacks/other/phpinfo.py", line 14, in process
    output.infot('Checking phpinfo..')
AttributeError: 'Output' object has no attribute 'infot'

**Comment by shenril** [comment]
Thanks for the feedback
I'll finish the refactoring to fix these and add some tests to prevent this in the future

**Comment by PierrePaul** [comment]
@shenril that's the str() issue I had. I started going throught them, but I'm not finished yet.
https://gist.github.com/PierrePaul/0d5c659f3403d0a86dc65cce585d3aed
(a merge request would make more sense, when it's done).

It's mostly two things, python3 requests returns a byte() object instead of str() (in python2). Sitadel tries to compare a `str` with `bytes`.

The other thing was list access and looping when reading file. I can't explain the reason though what changed between python2 and python3. Solution provided is not elegant works with minimal changes.

I havent touched the bruteforce module yet.

Many `re` expression needs to be redone as well.

**Comment by shenril** [comment]
@PierrePaul @sk3lk0 I fixed most of the errors in my commits this week
I 'll keep the ticket opened until I finish the automated testing for the attack modules

**Comment by sk3lk0** [comment]
i can test tool, if you want

**Comment by shenril** [comment]
I wrote tests to verify all the modules loaded and check it with travis
@sk3lk0 you can try again, I think I fixed all the errors you mentioned

**Comment by sk3lk0** [comment]
i test on site via http:
[i] Checking ldap injection...
cannot use a string pattern on a bytes-like object
[i] Checking php code injection...
cannot use a string pattern on a bytes-like object
[i] Checking remote file inclusion...
cannot use a string pattern on a bytes-like object
[i] Checking sql injection...
cannot use a string pattern on a bytes-like object
[i] Checking xpath injection...
cannot use a string pattern on a bytes-like object
[i] Checking cross site scripting...
cannot use a string pattern on a bytes-like object
[i] Scanning anonymous cipher vuln...

**Comment by shenril** [comment]
@sk3lk0 
Thank you for the feedback, I'm fixing this right away

**Comment by sk3lk0** [comment]
[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?page=home.php&popUpNotificationCode=HPH0
[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?page=login.php
[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?do=toggle-hints&page=home.php
[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?do=toggle-bubble-hints&page=home.php
[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?do=toggle-security&page=home.php
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%3Ch1%3E%3Ca+href%3D%22http%3A%2F%2Fwww.google.com%22%3EClick+Linguini%21%3C%2Fa%3E%3C%2Fh1%3E&page=%3Ch1%3E%3Ca+href%3D%22http%3A%2F%2Fwww.google.com%22%3EClick+Linguini%21%3C%2Fa%3E%3C%2Fh1%3E (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e6869e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking ldap injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5C21&page=%5C21 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e70fba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking php code injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=1%3Bphpinfo%28%29&page=1%3Bphpinfo%28%29 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e5b7080>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking remote file inclusion...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%27%2Fboot.ini%27%2C+%27%27%5D&page=%5B%27%2Fboot.ini%27%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e5b7a20>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking sql injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%27%22%2C+%27%27%5D&page=%5B%22%27%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e66fba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking xpath injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%27+or+%271%27%3D%271%22%2C+%27%27%5D&page=%5B%22%27+or+%271%27%3D%271%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e5530f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking cross site scripting...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%3Cscript%3Ealert%28%27xss%27%29%3C%2Fscript%3E%22%2C+%27%27%5D&page=%5B%22%3Cscript%3Ealert%28%27xss%27%29%3C%2Fscript%3E%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096e686ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by shenril** [comment]
well looks like the website refuse to answer or you're being blocked by firewall ... 
I can catch the error and consider the attack as failed i guess ?

**Comment by sk3lk0** [comment]
maybe this option will better? if timeout, script check file/dir  again

**Comment by sk3lk0** [comment]
test on https site
[i] Checking common backdoors...
[+] Found Backdoor at https://my https site/shell.php
[i] Checking common backup dirs..
HTTPSConnectionPool(host='my https site', port=443): Max retries exceeded with url: /public.backup/%0A (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff6ddcc470>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[i] Checking common backup files..
HTTPSConnectionPool(host='my https site', port=443): Max retries exceeded with url: /accounts.txt.7z%0A (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff6dda74e0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[i] Checking common dirs..
HTTPSConnectionPool(host='my https site', port=443): Max retries exceeded with url: /cgi-sys (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff6dda7128>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[i] Checking common files...
HTTPSConnectionPool(host='my https site', port=443): Max retries exceeded with url: /culeadora.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff6de4a278>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[i] Checking common log files..
HTTPSConnectionPool(host='my https site', port=443): Max retries exceeded with url: /.logs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff6de01eb8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by sk3lk0** [comment]
test on http

[+] That site is may be vulnerable to HTML Code Injection at http://ua111.ml/index.php?do=toggle-security&page=home.php
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%3Ch1%3E%3Ca+href%3D%22http%3A%2F%2Fwww.google.com%22%3EClick+Linguini%21%3C%2Fa%3E%3C%2Fh1%3E&page=%3Ch1%3E%3Ca+href%3D%22http%3A%2F%2Fwww.google.com%22%3EClick+Linguini%21%3C%2Fa%3E%3C%2Fh1%3E (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6845429a20>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking ldap injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5C21&page=%5C21 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68454c8fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking php code injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=1%3Bphpinfo%28%29&page=1%3Bphpinfo%28%29 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68452b5cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking remote file inclusion...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%27%2Fboot.ini%27%2C+%27%27%5D&page=%5B%27%2Fboot.ini%27%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6845429b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking sql injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%27%22%2C+%27%27%5D&page=%5B%22%27%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f684541cc18>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking xpath injection...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%27+or+%271%27%3D%271%22%2C+%27%27%5D&page=%5B%22%27+or+%271%27%3D%271%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68452414a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Checking cross site scripting...
HTTPSConnectionPool(host='ua111.ml', port=443): Max retries exceeded with url: /index.php?popUpNotificationCode=SSLE1&page=home.phpdo=%5B%22%3Cscript%3Ealert%28%27xss%27%29%3C%2Fscript%3E%22%2C+%27%27%5D&page=%5B%22%3Cscript%3Ealert%28%27xss%27%29%3C%2Fscript%3E%22%2C+%27%27%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68453b8da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[i] Scanning anonymous cipher vuln...

**Comment by shenril** [comment]
@sk3lk0 
When the connection is refused I'll consider that the scan is blocked, so I will abort the attack 
Retrying won't make things better I think 
Here is the PR related #16

**Comment by shenril** [comment]
I ll consider this a resolved for now
If you encounter other errors, let me know
